# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
namespace eval ::optrace {
  variable script "D:/neural_network/neural_network.runs/impl_1/neural_network.tcl"
  variable category "vivado_impl"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    } elseif { [info exist ::env(HOST)] } {
      set host $::env(HOST)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
OPTRACE "impl_1" END { }
}


OPTRACE "impl_1" START { ROLLUP_1 }
OPTRACE "Phase: Init Design" START { ROLLUP_AUTO }
start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param chipscope.maxJobs 3
  set_param runs.launchOptions { -jobs 12  }
OPTRACE "create in-memory project" START { }
  create_project -in_memory -part xc7a100tcsg324-1
  set_property board_part_repo_paths {C:/Users/nicoc/AppData/Roaming/Xilinx/Vivado/2023.1/xhub/board_store/xilinx_board_store} [current_project]
  set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
OPTRACE "create in-memory project" END { }
OPTRACE "set parameters" START { }
  set_property webtalk.parent_dir D:/neural_network/neural_network.cache/wt [current_project]
  set_property parent.project_path D:/neural_network/neural_network.xpr [current_project]
  set_property ip_output_repo D:/neural_network/neural_network.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES XPM_MEMORY [current_project]
OPTRACE "set parameters" END { }
OPTRACE "add files" START { }
  add_files -quiet D:/neural_network/neural_network.runs/synth_1/neural_network.dcp
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_0/memory_neuron_1_0.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/accumulator/accumulator.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/multiplier/multiplier.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_127/memory_neuron_1_127.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_126/memory_neuron_1_126.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_125/memory_neuron_1_125.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_124/memory_neuron_1_124.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_123/memory_neuron_1_123.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_122/memory_neuron_1_122.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_121/memory_neuron_1_121.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_120/memory_neuron_1_120.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_119/memory_neuron_1_119.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_118/memory_neuron_1_118.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_117/memory_neuron_1_117.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_116/memory_neuron_1_116.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_115/memory_neuron_1_115.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_114/memory_neuron_1_114.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_113/memory_neuron_1_113.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_112/memory_neuron_1_112.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_111/memory_neuron_1_111.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_110/memory_neuron_1_110.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_109/memory_neuron_1_109.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_108/memory_neuron_1_108.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_107/memory_neuron_1_107.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_106/memory_neuron_1_106.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_105/memory_neuron_1_105.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_104/memory_neuron_1_104.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_103/memory_neuron_1_103.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_102/memory_neuron_1_102.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_101/memory_neuron_1_101.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_100/memory_neuron_1_100.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_99/memory_neuron_1_99.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_98/memory_neuron_1_98.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_97/memory_neuron_1_97.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_96/memory_neuron_1_96.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_95/memory_neuron_1_95.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_94/memory_neuron_1_94.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_93/memory_neuron_1_93.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_92/memory_neuron_1_92.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_91/memory_neuron_1_91.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_90/memory_neuron_1_90.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_89/memory_neuron_1_89.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_88/memory_neuron_1_88.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_87/memory_neuron_1_87.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_86/memory_neuron_1_86.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_85/memory_neuron_1_85.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_84/memory_neuron_1_84.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_83/memory_neuron_1_83.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_82/memory_neuron_1_82.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_81/memory_neuron_1_81.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_80/memory_neuron_1_80.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_79/memory_neuron_1_79.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_78/memory_neuron_1_78.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_77/memory_neuron_1_77.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_76/memory_neuron_1_76.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_75/memory_neuron_1_75.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_74/memory_neuron_1_74.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_73/memory_neuron_1_73.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_72/memory_neuron_1_72.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_71/memory_neuron_1_71.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_70/memory_neuron_1_70.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_69/memory_neuron_1_69.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_68/memory_neuron_1_68.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_67/memory_neuron_1_67.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_66/memory_neuron_1_66.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_65/memory_neuron_1_65.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_64/memory_neuron_1_64.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_63/memory_neuron_1_63.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_62/memory_neuron_1_62.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_60/memory_neuron_1_60.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_59/memory_neuron_1_59.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_58/memory_neuron_1_58.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_57/memory_neuron_1_57.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_56/memory_neuron_1_56.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_55/memory_neuron_1_55.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_54/memory_neuron_1_54.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_53/memory_neuron_1_53.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_52/memory_neuron_1_52.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_51/memory_neuron_1_51.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_50/memory_neuron_1_50.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_49/memory_neuron_1_49.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_48/memory_neuron_1_48.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_47/memory_neuron_1_47.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_46/memory_neuron_1_46.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_45/memory_neuron_1_45.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_44/memory_neuron_1_44.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_43/memory_neuron_1_43.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_42/memory_neuron_1_42.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_41/memory_neuron_1_41.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_40/memory_neuron_1_40.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_39/memory_neuron_1_39.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_38/memory_neuron_1_38.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_37/memory_neuron_1_37.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_36/memory_neuron_1_36.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_35/memory_neuron_1_35.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_34/memory_neuron_1_34.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_33/memory_neuron_1_33.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_32/memory_neuron_1_32.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_31/memory_neuron_1_31.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_30/memory_neuron_1_30.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_29/memory_neuron_1_29.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_28/memory_neuron_1_28.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_27/memory_neuron_1_27.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_26/memory_neuron_1_26.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_25/memory_neuron_1_25.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_24/memory_neuron_1_24.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_23/memory_neuron_1_23.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_22/memory_neuron_1_22.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_21/memory_neuron_1_21.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_20/memory_neuron_1_20.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_19/memory_neuron_1_19.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_18/memory_neuron_1_18.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_17/memory_neuron_1_17.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_16/memory_neuron_1_16.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_15/memory_neuron_1_15.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_14/memory_neuron_1_14.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_13/memory_neuron_1_13.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_12/memory_neuron_1_12.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_11/memory_neuron_1_11.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_10/memory_neuron_1_10.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_9/memory_neuron_1_9.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_8/memory_neuron_1_8.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_7/memory_neuron_1_7.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_6/memory_neuron_1_6.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_5/memory_neuron_1_5.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_4/memory_neuron_1_4.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_3/memory_neuron_1_3.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_2/memory_neuron_1_2.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_1/memory_neuron_1_1.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_61/memory_neuron_1_61.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_memory/pixel_memory.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/output_layer_1/output_layer_1.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_1/memory_neuron_2_1.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_2/memory_neuron_2_2.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_3/memory_neuron_2_3.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_4/memory_neuron_2_4.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_5/memory_neuron_2_5.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_6/memory_neuron_2_6.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_7/memory_neuron_2_7.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_8/memory_neuron_2_8.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_9/memory_neuron_2_9.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/compare_0/compare_0.xci
  read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_0/memory_neuron_2_0.xci
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_0_final/pixel_test_0_final.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_0_final/pixel_test_0_final.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/blk_mem_gen_0_4/blk_mem_gen_0.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/blk_mem_gen_0_4/blk_mem_gen_0.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/floating_point_0_2/floating_point_0.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/floating_point_0_2/floating_point_0.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test/pixel_test.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test/pixel_test.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_1/pixel_test_1.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_1/pixel_test_1.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_2/pixel_test_2.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_2/pixel_test_2.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_3/pixel_test_3.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_3/pixel_test_3.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_4/pixel_test_4.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_4/pixel_test_4.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/ila_0_1/ila_0.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/ila_0_1/ila_0.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_1_final/pixel_test_1_final.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_1_final/pixel_test_1_final.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_4_final/pixel_test_4_final.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_4_final/pixel_test_4_final.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_5_final/pixel_test_5_final.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_5_final/pixel_test_5_final.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_6_final/pixel_test_6_final.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_6_final/pixel_test_6_final.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_7_final/pixel_test_7_final.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_7_final/pixel_test_7_final.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_8_final/pixel_test_8_final.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_8_final/pixel_test_8_final.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_9_final/pixel_test_9_final.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_9_final/pixel_test_9_final.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_2_final/pixel_test_2_final.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_2_final/pixel_test_2_final.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_3_final/pixel_test_3_final.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_3_final/pixel_test_3_final.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp]
  add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_11_final/pixel_test_11_final.dcp
  set_property netlist_only true [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_11_final/pixel_test_11_final.dcp]
OPTRACE "read constraints: implementation" START { }
  read_xdc D:/neural_network/neural_network.srcs/constrs_1/new/nexys4ddr.xdc
OPTRACE "read constraints: implementation" END { }
OPTRACE "add files" END { }
OPTRACE "link_design" START { }
  link_design -top neural_network -part xc7a100tcsg324-1 
OPTRACE "link_design" END { }
OPTRACE "gray box cells" START { }
OPTRACE "gray box cells" END { }
OPTRACE "init_design_reports" START { REPORT }
OPTRACE "init_design_reports" END { }
OPTRACE "init_design_write_hwdef" START { }
OPTRACE "init_design_write_hwdef" END { }
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

OPTRACE "Phase: Init Design" END { }
OPTRACE "Phase: Opt Design" START { ROLLUP_AUTO }
start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
OPTRACE "read constraints: opt_design" START { }
OPTRACE "read constraints: opt_design" END { }
OPTRACE "opt_design" START { }
  opt_design 
OPTRACE "opt_design" END { }
OPTRACE "read constraints: opt_design_post" START { }
OPTRACE "read constraints: opt_design_post" END { }
OPTRACE "opt_design reports" START { REPORT }
  create_report "impl_1_opt_report_drc_0" "report_drc -file neural_network_drc_opted.rpt -pb neural_network_drc_opted.pb -rpx neural_network_drc_opted.rpx"
OPTRACE "opt_design reports" END { }
OPTRACE "Opt Design: write_checkpoint" START { CHECKPOINT }
  write_checkpoint -force neural_network_opt.dcp
OPTRACE "Opt Design: write_checkpoint" END { }
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

OPTRACE "Phase: Opt Design" END { }
OPTRACE "Phase: Place Design" START { ROLLUP_AUTO }
start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
OPTRACE "read constraints: place_design" START { }
OPTRACE "read constraints: place_design" END { }
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
OPTRACE "implement_debug_core" START { }
    implement_debug_core 
OPTRACE "implement_debug_core" END { }
  } 
OPTRACE "place_design" START { }
  place_design 
OPTRACE "place_design" END { }
OPTRACE "read constraints: place_design_post" START { }
OPTRACE "read constraints: place_design_post" END { }
OPTRACE "place_design reports" START { REPORT }
  create_report "impl_1_place_report_io_0" "report_io -file neural_network_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file neural_network_utilization_placed.rpt -pb neural_network_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file neural_network_control_sets_placed.rpt"
OPTRACE "place_design reports" END { }
OPTRACE "Place Design: write_checkpoint" START { CHECKPOINT }
  write_checkpoint -force neural_network_placed.dcp
OPTRACE "Place Design: write_checkpoint" END { }
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

OPTRACE "Phase: Place Design" END { }
OPTRACE "Phase: Physical Opt Design" START { ROLLUP_AUTO }
start_step phys_opt_design
set ACTIVE_STEP phys_opt_design
set rc [catch {
  create_msg_db phys_opt_design.pb
OPTRACE "read constraints: phys_opt_design" START { }
OPTRACE "read constraints: phys_opt_design" END { }
OPTRACE "phys_opt_design" START { }
  phys_opt_design 
OPTRACE "phys_opt_design" END { }
OPTRACE "read constraints: phys_opt_design_post" START { }
OPTRACE "read constraints: phys_opt_design_post" END { }
OPTRACE "phys_opt_design report" START { REPORT }
OPTRACE "phys_opt_design report" END { }
OPTRACE "Post-Place Phys Opt Design: write_checkpoint" START { CHECKPOINT }
  write_checkpoint -force neural_network_physopt.dcp
OPTRACE "Post-Place Phys Opt Design: write_checkpoint" END { }
  close_msg_db -file phys_opt_design.pb
} RESULT]
if {$rc} {
  step_failed phys_opt_design
  return -code error $RESULT
} else {
  end_step phys_opt_design
  unset ACTIVE_STEP 
}

OPTRACE "Phase: Physical Opt Design" END { }
OPTRACE "Phase: Route Design" START { ROLLUP_AUTO }
start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
OPTRACE "read constraints: route_design" START { }
OPTRACE "read constraints: route_design" END { }
OPTRACE "route_design" START { }
  route_design 
OPTRACE "route_design" END { }
OPTRACE "read constraints: route_design_post" START { }
OPTRACE "read constraints: route_design_post" END { }
OPTRACE "route_design reports" START { REPORT }
  create_report "impl_1_route_report_drc_0" "report_drc -file neural_network_drc_routed.rpt -pb neural_network_drc_routed.pb -rpx neural_network_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file neural_network_methodology_drc_routed.rpt -pb neural_network_methodology_drc_routed.pb -rpx neural_network_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file neural_network_power_routed.rpt -pb neural_network_power_summary_routed.pb -rpx neural_network_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file neural_network_route_status.rpt -pb neural_network_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -report_unconstrained -file neural_network_timing_summary_routed.rpt -pb neural_network_timing_summary_routed.pb -rpx neural_network_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file neural_network_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file neural_network_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file neural_network_bus_skew_routed.rpt -pb neural_network_bus_skew_routed.pb -rpx neural_network_bus_skew_routed.rpx"
OPTRACE "route_design reports" END { }
OPTRACE "Route Design: write_checkpoint" START { CHECKPOINT }
  write_checkpoint -force neural_network_routed.dcp
OPTRACE "Route Design: write_checkpoint" END { }
OPTRACE "route_design misc" START { }
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
OPTRACE "route_design write_checkpoint" START { CHECKPOINT }
OPTRACE "route_design write_checkpoint" END { }
  write_checkpoint -force neural_network_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

OPTRACE "route_design misc" END { }
OPTRACE "Phase: Route Design" END { }
OPTRACE "Phase: Write Bitstream" START { ROLLUP_AUTO }
OPTRACE "write_bitstream setup" START { }
start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
OPTRACE "read constraints: write_bitstream" START { }
OPTRACE "read constraints: write_bitstream" END { }
  set_property XPM_LIBRARIES XPM_MEMORY [current_project]
  catch { write_mem_info -force -no_partial_mmi neural_network.mmi }
OPTRACE "write_bitstream setup" END { }
OPTRACE "write_bitstream" START { }
  write_bitstream -force neural_network.bit 
OPTRACE "write_bitstream" END { }
OPTRACE "write_bitstream misc" START { }
OPTRACE "read constraints: write_bitstream_post" START { }
OPTRACE "read constraints: write_bitstream_post" END { }
  catch {write_debug_probes -quiet -force neural_network}
  catch {file copy -force neural_network.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

OPTRACE "write_bitstream misc" END { }
OPTRACE "Phase: Write Bitstream" END { }
OPTRACE "impl_1" END { }
