# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/nexys4ddr.xdc

# IP: ip/pixel_test_0_final/pixel_test_0_final.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pixel_test_0_final || ORIG_REF_NAME==pixel_test_0_final} -quiet] -quiet
