# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/neural_network/neural_network.runs/synth_1/neural_network.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/neural_network/neural_network.cache/wt [current_project]
set_property parent.project_path D:/neural_network/neural_network.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/nicoc/AppData/Roaming/Xilinx/Vivado/2023.1/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo d:/neural_network/neural_network.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_0.coe
add_files D:/neural_network/neural_network.srcs/sources_1/ip/neuron_1_0.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_1.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_2.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_3.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_4.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_5.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_6.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_7.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_8.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_9.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_10.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_11.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_12.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_13.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_14.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_15.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_16.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_17.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_18.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_19.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_20.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_21.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_22.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_23.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_24.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_25.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_26.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_27.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_28.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_29.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_30.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_31.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_32.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_33.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_34.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_35.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_36.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_37.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_38.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_39.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_40.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_41.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_42.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_43.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_44.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_45.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_46.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_47.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_48.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_49.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_50.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_51.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_52.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_53.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_54.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_55.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_56.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_57.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_58.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_59.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_60.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_61.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_62.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_63.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_64.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_65.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_66.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_67.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_68.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_69.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_70.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_71.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_72.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_73.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_74.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_75.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_76.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_77.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_78.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_79.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_80.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_81.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_82.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_83.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_84.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_85.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_86.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_87.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_88.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_89.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_90.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_91.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_92.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_93.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_94.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_95.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_96.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_97.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_98.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_99.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_100.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_101.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_102.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_103.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_104.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_105.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_106.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_107.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_108.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_109.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_110.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_111.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_112.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_113.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_114.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_115.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_116.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_117.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_118.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_119.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_120.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_121.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_122.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_123.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_124.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_125.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_126.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_1/neuron_1_127.coe
add_files C:/Users/nicoc/Downloads/output.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_2/neuron_2_0.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_2/neuron_2_1.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_2/neuron_2_2.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_2/neuron_2_3.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_2/neuron_2_4.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_2/neuron_2_5.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_2/neuron_2_6.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_2/neuron_2_7.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_2/neuron_2_8.coe
add_files C:/Users/nicoc/Desktop/mnist/layer_2/neuron_2_9.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_0.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_127.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_126.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_125.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_124.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_123.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_122.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_121.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_120.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_119.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_118.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_117.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_116.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_115.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_114.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_113.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_112.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_111.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_110.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_109.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_108.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_107.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_106.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_105.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_104.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_103.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_102.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_101.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_100.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_99.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_98.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_97.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_96.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_95.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_94.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_93.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_92.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_91.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_90.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_89.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_88.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_87.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_86.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_85.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_84.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_83.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_82.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_81.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_80.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_79.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_78.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_77.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_76.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_75.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_74.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_73.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_72.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_71.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_70.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_69.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_68.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_67.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_66.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_65.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_64.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_63.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_62.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_60.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_59.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_58.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_57.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_56.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_55.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_54.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_53.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_52.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_51.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_50.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_49.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_48.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_47.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_46.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_45.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_44.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_43.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_42.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_41.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_40.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_39.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_38.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_37.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_36.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_35.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_34.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_33.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_32.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_31.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_30.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_29.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_28.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_27.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_26.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_25.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_24.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_23.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_22.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_21.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_20.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_19.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_18.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_17.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_16.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_15.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_14.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_13.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_12.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_11.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_10.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_9.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_8.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_7.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_6.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_5.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_4.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_3.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_2.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_1.coe
add_files D:/Desktop/mnist/layer_1/neuron_1_61.coe
add_files D:/Desktop/mnist/layer_2/neuron_2_0.coe
add_files D:/Desktop/mnist/layer_2/neuron_2_1.coe
add_files D:/Desktop/mnist/layer_2/neuron_2_2.coe
add_files D:/Desktop/mnist/layer_2/neuron_2_3.coe
add_files D:/Desktop/mnist/layer_2/neuron_2_4.coe
add_files D:/Desktop/mnist/layer_2/neuron_2_5.coe
add_files D:/Desktop/mnist/layer_2/neuron_2_6.coe
add_files D:/Desktop/mnist/layer_2/neuron_2_7.coe
add_files D:/Desktop/mnist/layer_2/neuron_2_8.coe
add_files D:/Desktop/mnist/layer_2/neuron_2_9.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_0.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_1.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_2.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_3.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_4.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_5.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_6.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_7.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_8.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_9.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_10.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_11.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_12.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_13.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_14.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_15.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_16.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_17.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_18.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_19.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_20.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_21.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_22.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_23.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_24.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_25.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_26.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_27.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_28.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_29.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_30.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_31.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_32.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_33.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_34.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_35.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_36.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_37.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_38.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_39.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_40.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_41.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_42.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_43.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_44.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_45.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_46.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_47.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_48.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_49.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_50.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_51.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_52.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_53.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_54.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_55.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_56.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_57.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_58.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_59.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_60.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_61.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_62.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_63.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_64.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_65.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_66.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_67.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_68.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_69.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_70.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_71.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_72.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_73.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_74.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_75.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_76.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_77.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_78.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_79.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_80.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_81.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_82.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_83.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_84.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_85.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_86.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_87.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_88.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_89.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_90.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_91.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_92.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_93.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_94.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_95.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_96.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_97.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_98.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_99.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_100.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_101.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_102.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_103.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_104.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_105.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_106.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_107.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_108.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_109.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_110.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_111.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_112.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_113.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_114.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_115.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_116.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_117.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_118.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_119.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_120.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_121.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_122.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_123.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_124.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_125.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_126.coe
add_files D:/neural_network/mnist/layer_1/neuron_1_127.coe
add_files D:/neural_network/mnist/layer_2/neuron_2_0.coe
add_files D:/neural_network/mnist/layer_2/neuron_2_1.coe
add_files D:/neural_network/mnist/layer_2/neuron_2_2.coe
add_files D:/neural_network/mnist/layer_2/neuron_2_3.coe
add_files D:/neural_network/mnist/layer_2/neuron_2_4.coe
add_files D:/neural_network/mnist/layer_2/neuron_2_5.coe
add_files D:/neural_network/mnist/layer_2/neuron_2_6.coe
add_files D:/neural_network/mnist/layer_2/neuron_2_7.coe
add_files D:/neural_network/mnist/layer_2/neuron_2_8.coe
add_files D:/neural_network/mnist/layer_2/neuron_2_9.coe
add_files c:/Users/nicoc/Desktop/mnist_application/mnist_image_2.coe
add_files c:/Users/nicoc/Desktop/mnist_application/mnist_image_3.coe
add_files c:/Users/nicoc/Desktop/mnist_application/mnist_image_4.coe
add_files c:/Users/nicoc/Desktop/mnist_application/mnist_image_test_1.coe
add_files c:/Users/nicoc/Desktop/mnist_image_test_1_FPGA_modified.coe
add_files c:/Users/nicoc/Desktop/mnist_application/mnist_image_0.coe
add_files c:/Users/nicoc/Desktop/mnist_application/mnist_image_5.coe
add_files c:/Users/nicoc/Desktop/mnist_application/mnist_image_6.coe
add_files c:/Users/nicoc/Desktop/mnist_application/mnist_image_7.coe
add_files c:/Users/nicoc/Desktop/mnist_application/mnist_image_8.coe
add_files c:/Users/nicoc/Desktop/mnist_application/mnist_image_9.coe
add_files c:/Users/nicoc/Desktop/mnist_images/mnist_image_1.coe
add_files c:/Users/nicoc/Desktop/mnist_images/mnist_image_0.coe
add_files c:/Users/nicoc/Desktop/mnist_images/mnist_image_2.coe
add_files c:/Users/nicoc/Desktop/mnist_images/mnist_image_3.coe
add_files c:/Users/nicoc/Desktop/mnist_images/mnist_image_4.coe
add_files c:/Users/nicoc/Desktop/mnist_images/mnist_image_5.coe
add_files c:/Users/nicoc/Desktop/mnist_images/mnist_image_6.coe
add_files c:/Users/nicoc/Desktop/mnist_images/mnist_image_7.coe
add_files c:/Users/nicoc/Desktop/mnist_images/mnist_image_8.coe
add_files c:/Users/nicoc/Desktop/mnist_images/mnist_image_9.coe
add_files c:/Users/nicoc/Desktop/mnist_images/mnist_image_11.coe
add_files c:/Users/nicoc/Desktop/mnist_application/mnist_image.coe
add_files -quiet d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_0_final/pixel_test_0_final.dcp
set_property used_in_implementation false [get_files d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_0_final/pixel_test_0_final.dcp]
read_vhdl -library xil_defaultlib {
  D:/neural_network/neural_network.srcs/sources_1/new/types_pkg.vhd
  D:/neural_network/neural_network.srcs/sources_1/new/compare_digit.vhd
  D:/neural_network/neural_network.srcs/sources_1/new/neuron_layer_1.vhd
  D:/neural_network/neural_network.srcs/sources_1/new/layer2.vhd
  D:/neural_network/neural_network.srcs/sources_1/new/uart_image_receiver.vhd
  D:/neural_network/neural_network.srcs/sources_1/new/neural_network.vhd
  D:/neural_network/neural_network.srcs/sources_1/new/layer1.vhd
}
read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_0/memory_neuron_1_0.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_0/memory_neuron_1_0_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/blk_mem_gen_0_4/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/blk_mem_gen_0_4/blk_mem_gen_0_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/floating_point_0_2/floating_point_0.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/floating_point_0_2/floating_point_0_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/accumulator/accumulator.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/accumulator/accumulator_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/multiplier/multiplier.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/multiplier/multiplier_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_127/memory_neuron_1_127.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_127/memory_neuron_1_127_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_126/memory_neuron_1_126.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_126/memory_neuron_1_126_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_125/memory_neuron_1_125.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_125/memory_neuron_1_125_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_124/memory_neuron_1_124.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_124/memory_neuron_1_124_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_123/memory_neuron_1_123.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_123/memory_neuron_1_123_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_122/memory_neuron_1_122.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_122/memory_neuron_1_122_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_121/memory_neuron_1_121.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_121/memory_neuron_1_121_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_120/memory_neuron_1_120.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_120/memory_neuron_1_120_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_119/memory_neuron_1_119.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_119/memory_neuron_1_119_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_118/memory_neuron_1_118.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_118/memory_neuron_1_118_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_117/memory_neuron_1_117.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_117/memory_neuron_1_117_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_116/memory_neuron_1_116.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_116/memory_neuron_1_116_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_115/memory_neuron_1_115.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_115/memory_neuron_1_115_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_114/memory_neuron_1_114.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_114/memory_neuron_1_114_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_113/memory_neuron_1_113.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_113/memory_neuron_1_113_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_112/memory_neuron_1_112.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_112/memory_neuron_1_112_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_111/memory_neuron_1_111.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_111/memory_neuron_1_111_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_110/memory_neuron_1_110.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_110/memory_neuron_1_110_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_109/memory_neuron_1_109.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_109/memory_neuron_1_109_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_108/memory_neuron_1_108.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_108/memory_neuron_1_108_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_107/memory_neuron_1_107.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_107/memory_neuron_1_107_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_106/memory_neuron_1_106.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_106/memory_neuron_1_106_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_105/memory_neuron_1_105.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_105/memory_neuron_1_105_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_104/memory_neuron_1_104.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_104/memory_neuron_1_104_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_103/memory_neuron_1_103.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_103/memory_neuron_1_103_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_102/memory_neuron_1_102.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_102/memory_neuron_1_102_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_101/memory_neuron_1_101.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_101/memory_neuron_1_101_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_100/memory_neuron_1_100.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_100/memory_neuron_1_100_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_99/memory_neuron_1_99.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_99/memory_neuron_1_99_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_98/memory_neuron_1_98.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_98/memory_neuron_1_98_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_97/memory_neuron_1_97.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_97/memory_neuron_1_97_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_96/memory_neuron_1_96.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_96/memory_neuron_1_96_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_95/memory_neuron_1_95.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_95/memory_neuron_1_95_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_94/memory_neuron_1_94.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_94/memory_neuron_1_94_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_93/memory_neuron_1_93.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_93/memory_neuron_1_93_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_92/memory_neuron_1_92.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_92/memory_neuron_1_92_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_91/memory_neuron_1_91.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_91/memory_neuron_1_91_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_90/memory_neuron_1_90.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_90/memory_neuron_1_90_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_89/memory_neuron_1_89.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_89/memory_neuron_1_89_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_88/memory_neuron_1_88.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_88/memory_neuron_1_88_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_87/memory_neuron_1_87.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_87/memory_neuron_1_87_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_86/memory_neuron_1_86.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_86/memory_neuron_1_86_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_85/memory_neuron_1_85.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_85/memory_neuron_1_85_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_84/memory_neuron_1_84.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_84/memory_neuron_1_84_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_83/memory_neuron_1_83.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_83/memory_neuron_1_83_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_82/memory_neuron_1_82.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_82/memory_neuron_1_82_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_81/memory_neuron_1_81.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_81/memory_neuron_1_81_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_80/memory_neuron_1_80.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_80/memory_neuron_1_80_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_79/memory_neuron_1_79.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_79/memory_neuron_1_79_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_78/memory_neuron_1_78.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_78/memory_neuron_1_78_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_77/memory_neuron_1_77.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_77/memory_neuron_1_77_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_76/memory_neuron_1_76.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_76/memory_neuron_1_76_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_75/memory_neuron_1_75.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_75/memory_neuron_1_75_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_74/memory_neuron_1_74.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_74/memory_neuron_1_74_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_73/memory_neuron_1_73.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_73/memory_neuron_1_73_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_72/memory_neuron_1_72.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_72/memory_neuron_1_72_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_71/memory_neuron_1_71.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_71/memory_neuron_1_71_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_70/memory_neuron_1_70.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_70/memory_neuron_1_70_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_69/memory_neuron_1_69.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_69/memory_neuron_1_69_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_68/memory_neuron_1_68.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_68/memory_neuron_1_68_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_67/memory_neuron_1_67.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_67/memory_neuron_1_67_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_66/memory_neuron_1_66.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_66/memory_neuron_1_66_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_65/memory_neuron_1_65.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_65/memory_neuron_1_65_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_64/memory_neuron_1_64.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_64/memory_neuron_1_64_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_63/memory_neuron_1_63.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_63/memory_neuron_1_63_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_62/memory_neuron_1_62.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_62/memory_neuron_1_62_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_60/memory_neuron_1_60.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_60/memory_neuron_1_60_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_59/memory_neuron_1_59.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_59/memory_neuron_1_59_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_58/memory_neuron_1_58.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_58/memory_neuron_1_58_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_57/memory_neuron_1_57.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_57/memory_neuron_1_57_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_56/memory_neuron_1_56.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_56/memory_neuron_1_56_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_55/memory_neuron_1_55.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_55/memory_neuron_1_55_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_54/memory_neuron_1_54.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_54/memory_neuron_1_54_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_53/memory_neuron_1_53.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_53/memory_neuron_1_53_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_52/memory_neuron_1_52.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_52/memory_neuron_1_52_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_51/memory_neuron_1_51.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_51/memory_neuron_1_51_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_50/memory_neuron_1_50.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_50/memory_neuron_1_50_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_49/memory_neuron_1_49.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_49/memory_neuron_1_49_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_48/memory_neuron_1_48.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_48/memory_neuron_1_48_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_47/memory_neuron_1_47.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_47/memory_neuron_1_47_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_46/memory_neuron_1_46.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_46/memory_neuron_1_46_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_45/memory_neuron_1_45.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_45/memory_neuron_1_45_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_44/memory_neuron_1_44.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_44/memory_neuron_1_44_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_43/memory_neuron_1_43.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_43/memory_neuron_1_43_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_42/memory_neuron_1_42.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_42/memory_neuron_1_42_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_41/memory_neuron_1_41.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_41/memory_neuron_1_41_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_40/memory_neuron_1_40.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_40/memory_neuron_1_40_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_39/memory_neuron_1_39.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_39/memory_neuron_1_39_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_38/memory_neuron_1_38.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_38/memory_neuron_1_38_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_37/memory_neuron_1_37.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_37/memory_neuron_1_37_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_36/memory_neuron_1_36.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_36/memory_neuron_1_36_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_35/memory_neuron_1_35.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_35/memory_neuron_1_35_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_34/memory_neuron_1_34.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_34/memory_neuron_1_34_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_33/memory_neuron_1_33.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_33/memory_neuron_1_33_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_32/memory_neuron_1_32.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_32/memory_neuron_1_32_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_31/memory_neuron_1_31.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_31/memory_neuron_1_31_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_30/memory_neuron_1_30.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_30/memory_neuron_1_30_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_29/memory_neuron_1_29.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_29/memory_neuron_1_29_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_28/memory_neuron_1_28.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_28/memory_neuron_1_28_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_27/memory_neuron_1_27.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_27/memory_neuron_1_27_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_26/memory_neuron_1_26.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_26/memory_neuron_1_26_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_25/memory_neuron_1_25.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_25/memory_neuron_1_25_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_24/memory_neuron_1_24.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_24/memory_neuron_1_24_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_23/memory_neuron_1_23.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_23/memory_neuron_1_23_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_22/memory_neuron_1_22.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_22/memory_neuron_1_22_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_21/memory_neuron_1_21.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_21/memory_neuron_1_21_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_20/memory_neuron_1_20.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_20/memory_neuron_1_20_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_19/memory_neuron_1_19.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_19/memory_neuron_1_19_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_18/memory_neuron_1_18.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_18/memory_neuron_1_18_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_17/memory_neuron_1_17.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_17/memory_neuron_1_17_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_16/memory_neuron_1_16.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_16/memory_neuron_1_16_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_15/memory_neuron_1_15.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_15/memory_neuron_1_15_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_14/memory_neuron_1_14.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_14/memory_neuron_1_14_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_13/memory_neuron_1_13.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_13/memory_neuron_1_13_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_12/memory_neuron_1_12.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_12/memory_neuron_1_12_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_11/memory_neuron_1_11.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_11/memory_neuron_1_11_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_10/memory_neuron_1_10.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_10/memory_neuron_1_10_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_9/memory_neuron_1_9.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_9/memory_neuron_1_9_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_8/memory_neuron_1_8.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_8/memory_neuron_1_8_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_7/memory_neuron_1_7.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_7/memory_neuron_1_7_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_6/memory_neuron_1_6.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_6/memory_neuron_1_6_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_5/memory_neuron_1_5.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_5/memory_neuron_1_5_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_4/memory_neuron_1_4.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_4/memory_neuron_1_4_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_3/memory_neuron_1_3.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_3/memory_neuron_1_3_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_2/memory_neuron_1_2.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_2/memory_neuron_1_2_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_1/memory_neuron_1_1.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_1/memory_neuron_1_1_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_61/memory_neuron_1_61.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_61/memory_neuron_1_61_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_memory/pixel_memory.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_memory/pixel_memory_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/output_layer_1/output_layer_1.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/output_layer_1/output_layer_1_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test/pixel_test.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test/pixel_test_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_1/memory_neuron_2_1.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_2_1/memory_neuron_2_1_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_2/memory_neuron_2_2.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_2_2/memory_neuron_2_2_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_3/memory_neuron_2_3.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_2_3/memory_neuron_2_3_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_4/memory_neuron_2_4.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_2_4/memory_neuron_2_4_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_5/memory_neuron_2_5.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_2_5/memory_neuron_2_5_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_6/memory_neuron_2_6.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_2_6/memory_neuron_2_6_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_7/memory_neuron_2_7.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_2_7/memory_neuron_2_7_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_8/memory_neuron_2_8.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_2_8/memory_neuron_2_8_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_9/memory_neuron_2_9.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_2_9/memory_neuron_2_9_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/compare_0/compare_0.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/compare_0/compare_0_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_1/pixel_test_1.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_1/pixel_test_1_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_2/pixel_test_2.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_2/pixel_test_2_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_3/pixel_test_3.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_3/pixel_test_3_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_4/pixel_test_4.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_4/pixel_test_4_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/ila_0_1/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/ila_0_1/ila_0_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_1_final/pixel_test_1_final.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_1_final/pixel_test_1_final_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_4_final/pixel_test_4_final.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_4_final/pixel_test_4_final_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_5_final/pixel_test_5_final.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_5_final/pixel_test_5_final_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_6_final/pixel_test_6_final.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_6_final/pixel_test_6_final_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_7_final/pixel_test_7_final.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_7_final/pixel_test_7_final_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_8_final/pixel_test_8_final.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_8_final/pixel_test_8_final_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_9_final/pixel_test_9_final.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_9_final/pixel_test_9_final_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_2_final/pixel_test_2_final.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_2_final/pixel_test_2_final_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_3_final/pixel_test_3_final.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_3_final/pixel_test_3_final_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/pixel_test_11_final/pixel_test_11_final.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/pixel_test_11_final/pixel_test_11_final_ooc.xdc]

read_ip -quiet D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_2_0/memory_neuron_2_0.xci
set_property used_in_implementation false [get_files -all d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_2_0/memory_neuron_2_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/neural_network/neural_network.srcs/constrs_1/new/nexys4ddr.xdc
set_property used_in_implementation false [get_files D:/neural_network/neural_network.srcs/constrs_1/new/nexys4ddr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/neural_network/neural_network.srcs/utils_1/imports/synth_1/neural_network.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top neural_network -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef neural_network.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file neural_network_utilization_synth.rpt -pb neural_network_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
