# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_22/memory_neuron_1_22.xci
# IP: The module: 'memory_neuron_1_22' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_22/memory_neuron_1_22_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_neuron_1_22'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/neural_network/neural_network.srcs/sources_1/ip/memory_neuron_1_22/memory_neuron_1_22.xci
# IP: The module: 'memory_neuron_1_22' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/neural_network/neural_network.gen/sources_1/ip/memory_neuron_1_22/memory_neuron_1_22_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_neuron_1_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
