# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/neural_network/neural_network.srcs/sources_1/ip/accumulator/accumulator.xci
# IP: The module: 'accumulator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/neural_network/neural_network.gen/sources_1/ip/accumulator/accumulator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accumulator'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/neural_network/neural_network.srcs/sources_1/ip/accumulator/accumulator.xci
# IP: The module: 'accumulator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/neural_network/neural_network.gen/sources_1/ip/accumulator/accumulator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accumulator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
