# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/neural_network/neural_network.srcs/sources_1/ip/compare_0/compare_0.xci
# IP: The module: 'compare_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/neural_network/neural_network.gen/sources_1/ip/compare_0/compare_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'compare_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/neural_network/neural_network.srcs/sources_1/ip/compare_0/compare_0.xci
# IP: The module: 'compare_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/neural_network/neural_network.gen/sources_1/ip/compare_0/compare_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'compare_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
