# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/neural_network/neural_network.srcs/sources_1/ip/pixel_memory/pixel_memory.xci
# IP: The module: 'pixel_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/neural_network/neural_network.gen/sources_1/ip/pixel_memory/pixel_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixel_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/neural_network/neural_network.srcs/sources_1/ip/pixel_memory/pixel_memory.xci
# IP: The module: 'pixel_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/neural_network/neural_network.gen/sources_1/ip/pixel_memory/pixel_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixel_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
